# Generated by Django 5.1.1 on 2024-10-02 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('homepage', models.URLField()),
                ('password', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('homepage', models.URLField()),
                ('text', models.TextField()),
                ('isAnswer', models.BooleanField(default=False)),
                ('answerTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commentariesApp.message')),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='commentariesApp.user')),
            ],
        ),
    ]
