# Generated by Django 5.1.1 on 2024-10-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentariesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='homepage',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='homepage',
            field=models.URLField(unique=True),
        ),
    ]
