# Generated by Django 5.1.1 on 2024-10-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentariesApp', '0002_alter_message_homepage_alter_user_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
