# Generated by Django 5.1.1 on 2024-10-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentariesApp', '0003_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='homepage',
            field=models.URLField(),
        ),
    ]
