# Generated by Django 5.1.1 on 2024-10-03 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentariesApp', '0004_alter_user_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='homepage',
        ),
    ]
