# Generated by Django 5.1.1 on 2024-10-07 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentariesApp', '0006_message_hasanswers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='answerTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='commentariesApp.message'),
        ),
    ]
